# Generated by Django 2.2.7 on 2019-11-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='departure_date',
            new_name='departureDate',
        ),
        migrations.RemoveField(
            model_name='search',
            name='return_date',
        ),
        migrations.AddField(
            model_name='search',
            name='returnDate',
            field=models.CharField(default='undefined', max_length=20),
        ),
    ]
