# Generated by Django 2.2.7 on 2019-11-16 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20191115_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='returnDate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='search',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='searches', to=settings.AUTH_USER_MODEL),
        ),
    ]
