# Generated by Django 2.2.7 on 2019-12-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_auto_20191116_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy_Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('departure_date', models.CharField(max_length=20)),
                ('return_date', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(max_length=20)),
            ],
        ),
    ]
